server:
  port: 3000

db:
  type: "postgres"
  host: "postgres"
  port: 5432
  database: "studentmgmt_db"
  username: "studentmgmt_db_user"
  synchronize: true

notifications:
  enabled: true

authentication:
  url: "http://sparky-service:8080"

logger:
  levels:
    - log
    - error
    - warn
    - debug
    - verbose
  requests: false
  dbErrors: true
